const isTesting = import.meta.env.VITE_TESTING === "true";
const permissionBased = import.meta.env.VITE_PERMISSION_BASED !== "false";
const devMode = import.meta.env.DEV;
const globalDateInputFormat = "yyyy-MM-dd'T'HH:mm:ss";
const globalDateDisplayFormat = "PPP";
const dummyValue =
  "Lorem ipsum dolor sit amet, qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.";
const salesData = [
  {
    name: "Olivia Martinmm",
    email: "olivia.martin@email.com",
    amount: "+$1,999.00",
    avatarSrc:
      "https://i0.wp.com/www.miwatj.com.au/wp-content/uploads/placeholder-person.png?w=1024&ssl=1",
  },
  {
    name: "Jackson Lee",
    email: "jackson.lee@email.com",
    amount: "+$39.00",
    avatarSrc:
      "https://i0.wp.com/www.miwatj.com.au/wp-content/uploads/placeholder-person.png?w=1024&ssl=1",
  },
  {
    name: "Isabella Nguyen",
    email: "isabella.nguyen@email.com",
    amount: "+$299.00",
    avatarSrc:
      "https://i0.wp.com/www.miwatj.com.au/wp-content/uploads/placeholder-person.png?w=1024&ssl=1",
  },
  {
    name: "William Kim",
    email: "will@email.com",
    amount: "+$99.00",
    avatarSrc:
      "https://i0.wp.com/www.miwatj.com.au/wp-content/uploads/placeholder-person.png?w=1024&ssl=1",
  },
  {
    name: "Sofia Davis",
    email: "sofia.davis@email.com",
    amount: "+$39.00",
    avatarSrc:
      "https://i0.wp.com/www.miwatj.com.au/wp-content/uploads/placeholder-person.png?w=1024&ssl=1",
  },
];
const privacyPolicyData = {
  privacyPolicy:
    '<h1>PRIVACY POLICY</h1><h2>LAST UPDATED: 22 MAY 2018</h2><p>Your privacy is important to us. We respect and are committed to protecting your privacy. This privacy statement explains what personal data that this website habtoorhospitality.com collects from you and how we use that data.</p><p>The following discloses the information gathering and dissemination practices of Habtoorhospitality.com (which is referred to as “we”, “our”, or “us”) on the website www.habtoorhospitality.com and our member services– (“Services”) associated with the site. It also describes the choices available to you regarding our use of your information and how you can access and update this information.</p><h2>PERSONAL IDENTIFICATION INFORMATION</h2><p>We may collect personal identification information from users in a variety of ways, including, but not limited to, when Users visit our site, register on the site, fill out a form, and about other activities, services, features or resources we make available on our Site. Users have the option to navigate our site anonymously. We will collect personal identification information from users only if they voluntarily submit such information to us. These voluntary data include fields as name, email, phone and company information, email address in order to be used for permission-based subscription to our email alerts, e-newsletters, and promotional emails, and logins to access portions of the site.</p><p>Users can always refuse to supply personally identification information, except that it may prevent them from engaging in certain site related activities. We never obtain data from third parties.</p><p>For each visitor to our web pages, our web server automatically recognizes and collects only the visitor’s IP address, aggregate information on what pages visitors access, information volunteered by the visitor,</p><h2>NON-PERSONAL IDENTIFICATION INFORMATION</h2><p>We may collect non-personal identification information about Users whenever they interact with our Site. Non-personal identification information may include the browser name, operating system or any such information, which are not connected to identify or trace you as a person.</p><h2>WEB BROWSER COOKIES</h2><p>Our Site may use “cookies” to enhance User experience. User’s web browser places cookies on their hard drive for record-keeping purposes and sometimes to track information about them. User may choose to set their web browser to refuse cookies, or to alert you when cookies are being sent. If they do so, note that some parts of the Site may not function properly.</p><h2>WHY ARE WE COLLECTING DATA?</h2><p>Al Habtoor Group may collect and use user’s personal information for the following purposes and nothing else:</p><ul><li>To improve customer service – Information you provide helps us respond to your customer service requests and support needs more efficiently.</li><li>To personalise user experience – We may use information in the aggregate to understand how our Users as a group use the services and resources provided on our Site.</li><li>To improve our Site – We may use feedback you provide to improve our products and services.</li><li>To send periodic emails – We may use the email address to respond to their inquiries, questions, and/or other requests.</li></ul><h2>HOW WE PROTECT YOUR INFORMATION</h2><p>We adopt appropriate data collection, storage and processing practices and security measures to protect against unauthorised access, alteration, disclosure or destruction of your personal information, username, password, transaction information and data stored on our Site.</p><h2>SHARING YOUR PERSONAL INFORMATION</h2><p>We do not sell, trade, or rent data to others than used by our data controllers for legitimate purposes as mentioned in this document.</p><h2>INFORMATION COLLECTION MODEL</h2><p>As a subscribing user to this website’s email marketing system driven by a pop-up form, we acknowledge that you have the right to access your personal information. An individual who no longer seeks to receive emails from us may auto-unsubscribe from email lists (see the Opting Out section below).</p><h2>INFORMATION SHARING AND DISCLOSURE</h2><p>We will never use, sell, share, disclose, or rent any internal or customer supplied data to any clients, prospects, or other third parties other than to any venture arising from the constituent hotels within this platform. We will share your information with third parties only in the ways that are described in this privacy policy. If Habtoorhospitality.com is involved in a merger, acquisition, or sale of all or a portion of its assets, you will be notified via email and/or a prominent notice on our website of any change in ownership or uses of your information, as well as any choices you may have regarding your information.</p><h2>THIRD PARTY WEBSITES</h2><p>Users may find advertising or other content on our Site that link to the sites and services of our partners, suppliers, advertisers, sponsors, licensors and other third parties. We do not control the content or links that appear on these sites and are not responsible for the practices employed by websites linked to or from our Site. In addition, these sites or services, including their content and links, may be constantly changing. These sites and services may have their own privacy policies and customer service policies. Browsing and interaction on any other website, including websites which have a link to our Site, is subject to that website’s own terms and policies.</p><h2>HOW TO ACCESS &amp; CONTROL YOUR PERSONAL DATA</h2><p>You can view, edit, or delete your (whatever minimalistic) personal data online. However, our systems require a double layer verification to access this section of the system. You can also make choices about our collection and use of your data.</p><h2>REMOVE AND FORGET &amp; OPTING OUT</h2><p>You can always choose whether you wish to receive promotional email from us. If you wish to subscribe to our email alerts, e-newsletters, and promotional communications, we will use your name and email address to send them to you. Out of respect for your privacy, if you no longer wish to receive our email alerts, e-newsletters, and promotional communications, you can easily opt-out by using the Unsubscribe link included in each communication, reply to the email requesting to be removed from the list, contact us at mailing@habtoorhospitality.com</p><p>We will not retain any of your information thereon on any of our systems, except the log of your request for removal.</p><h2>EU RESIDENTS / GDPR</h2><p>Though made applicable to all, acknowledging to (General Data Protection Regulation) GDPR of the European Union (EU), we emphasise that EU residents have rights to access personal data about them, and to limit use and disclosure of their personal data. We are committed to respect those rights. We acknowledge potential liability in cases of onward transfer of personal data to third parties who do not meet the criteria as set forth in this Policy.</p><p>We use an annual self-assessment to review its compliance with this Policy. Any employee who violates this policy will be subject to discipline, up to and including termination of employment.</p><h2>USER ACCESS AND CHOICE</h2><p>Upon request we will provide you with information about whether we hold any of your personal information. If your information changes, you may correct, update, amend, remove, or ask to have it removed by making the change on your user account settings page, by emailing our Customer Support Team at mailing@habtoorhospitality.com or by contacting us by telephone or postal mail at the contact information listed below. If you no longer desire our Service, please contact us directly.</p><p>We will retain your information for as long as your account is active, as needed to provide you Services and as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements.</p><h2>CONFIDENTIALITY AND SECURITY</h2><p>We warrant that all customer data remains the property of our customers. We also will not rent, sell, transfer, or otherwise expose the contents of the tracking information resulting from click through, message opened, message read, or eCommerce conversions.</p><p>In general, we do not collect data on this website. However, we follow generally accepted standards to protect the information submitted to us, both during transmission and once we receive it. This website www.habtoorhospitality.com provides an SSL encrypted, password-protected mechanism. We seek to use reasonable organizational, technical and administrative measures to protect Personal Information within our organization. Unfortunately, no data transmission or storage system can be guaranteed to be 100% secure.</p><h2>SOCIAL MEDIA FEATURES</h2><p>Our website includes social media features, such as links to our Facebook, YouTube, Google+, Google Blogger, LinkedIn and Twitter pages. These features may collect your IP address, which page you are visiting on our site, and may set a cookie to enable the feature to function properly. Social media features and widgets are either hosted by a third party or hosted directly on our site. Your interactions with these features are governed by the privacy policy of the company providing it.</p><h2>UNSOLICITED COMMERCIAL EMAIL (SPAM)</h2><p>Habtoorhospitality.com is committed to providing a permission-based model for email marketing. To that end, we carry a strict anti-spam policy for all our clients. We have explicitly prohibited our staff from sending any unsolicited material to users who have not expressed their permission to receive communications from them.</p><h2>UPDATES TO THIS PRIVACY STATEMENT</h2><p>We may change this Privacy Statement. The “LAST UPDATED” legend at the top of this page indicates when this Privacy Statement was last revised. Any changes will become effective when we post the revised Privacy Statement on the Online Services. Your use of the Services following these changes means that you accept the revised Privacy Statement. Because email communications are not always secure, please do not include credit card or other sensitive information in your emails to us.</p><h2>YOUR ACCEPTANCE OF THESE TERMS</h2><p>By using this Site, you signify your acceptance of this policy and terms of service. If you do not agree to this policy, please do not use our Site. Your continued use of the Site following the posting of changes to this policy will be deemed your acceptance of those changes.</p><h2>CONTACTING US</h2><p>We have created this privacy policy so that you can understand the care with which we intend to treat your information. To report any abuse or violations, or to contact us with any questions or concerns regarding this privacy policy, please contact us at:</p><p>Al Habtoor Group</p><p>Al Safa 2, Al Wasl Road,</p><p>Dubai,</p><p>United Arab Emirates</p><p>Data Controller: abuse@habtoorhospitality.com</p><p>Phone: +971 4704 8888</p><ul><li class="ql-align-center"><br></li></ul><p><br></p>',
};
const termsAndConditionsData = {
  termsAndConditions:
    '<h1>TERMS & CONDITIONS</h1><h2>LAST UPDATED: 22 MAY 2018</h2><p>Your privacy is important to us. We respect and are committed to protecting your privacy. This privacy statement explains what personal data that this website habtoorhospitality.com collects from you and how we use that data.</p><p>The following discloses the information gathering and dissemination practices of Habtoorhospitality.com (which is referred to as “we”, “our”, or “us”) on the website www.habtoorhospitality.com and our member services– (“Services”) associated with the site. It also describes the choices available to you regarding our use of your information and how you can access and update this information.</p><h2>PERSONAL IDENTIFICATION INFORMATION</h2><p>We may collect personal identification information from users in a variety of ways, including, but not limited to, when Users visit our site, register on the site, fill out a form, and about other activities, services, features or resources we make available on our Site. Users have the option to navigate our site anonymously. We will collect personal identification information from users only if they voluntarily submit such information to us. These voluntary data include fields as name, email, phone and company information, email address in order to be used for permission-based subscription to our email alerts, e-newsletters, and promotional emails, and logins to access portions of the site.</p><p>Users can always refuse to supply personally identification information, except that it may prevent them from engaging in certain site related activities. We never obtain data from third parties.</p><p>For each visitor to our web pages, our web server automatically recognizes and collects only the visitor’s IP address, aggregate information on what pages visitors access, information volunteered by the visitor,</p><h2>NON-PERSONAL IDENTIFICATION INFORMATION</h2><p>We may collect non-personal identification information about Users whenever they interact with our Site. Non-personal identification information may include the browser name, operating system or any such information, which are not connected to identify or trace you as a person.</p><h2>WEB BROWSER COOKIES</h2><p>Our Site may use “cookies” to enhance User experience. User’s web browser places cookies on their hard drive for record-keeping purposes and sometimes to track information about them. User may choose to set their web browser to refuse cookies, or to alert you when cookies are being sent. If they do so, note that some parts of the Site may not function properly.</p><h2>WHY ARE WE COLLECTING DATA?</h2><p>Al Habtoor Group may collect and use user’s personal information for the following purposes and nothing else:</p><ul><li>To improve customer service – Information you provide helps us respond to your customer service requests and support needs more efficiently.</li><li>To personalise user experience – We may use information in the aggregate to understand how our Users as a group use the services and resources provided on our Site.</li><li>To improve our Site – We may use feedback you provide to improve our products and services.</li><li>To send periodic emails – We may use the email address to respond to their inquiries, questions, and/or other requests.</li></ul><h2>HOW WE PROTECT YOUR INFORMATION</h2><p>We adopt appropriate data collection, storage and processing practices and security measures to protect against unauthorised access, alteration, disclosure or destruction of your personal information, username, password, transaction information and data stored on our Site.</p><h2>SHARING YOUR PERSONAL INFORMATION</h2><p>We do not sell, trade, or rent data to others than used by our data controllers for legitimate purposes as mentioned in this document.</p><h2>INFORMATION COLLECTION MODEL</h2><p>As a subscribing user to this website’s email marketing system driven by a pop-up form, we acknowledge that you have the right to access your personal information. An individual who no longer seeks to receive emails from us may auto-unsubscribe from email lists (see the Opting Out section below).</p><h2>INFORMATION SHARING AND DISCLOSURE</h2><p>We will never use, sell, share, disclose, or rent any internal or customer supplied data to any clients, prospects, or other third parties other than to any venture arising from the constituent hotels within this platform. We will share your information with third parties only in the ways that are described in this privacy policy. If Habtoorhospitality.com is involved in a merger, acquisition, or sale of all or a portion of its assets, you will be notified via email and/or a prominent notice on our website of any change in ownership or uses of your information, as well as any choices you may have regarding your information.</p><h2>THIRD PARTY WEBSITES</h2><p>Users may find advertising or other content on our Site that link to the sites and services of our partners, suppliers, advertisers, sponsors, licensors and other third parties. We do not control the content or links that appear on these sites and are not responsible for the practices employed by websites linked to or from our Site. In addition, these sites or services, including their content and links, may be constantly changing. These sites and services may have their own privacy policies and customer service policies. Browsing and interaction on any other website, including websites which have a link to our Site, is subject to that website’s own terms and policies.</p><h2>HOW TO ACCESS &amp; CONTROL YOUR PERSONAL DATA</h2><p>You can view, edit, or delete your (whatever minimalistic) personal data online. However, our systems require a double layer verification to access this section of the system. You can also make choices about our collection and use of your data.</p><h2>REMOVE AND FORGET &amp; OPTING OUT</h2><p>You can always choose whether you wish to receive promotional email from us. If you wish to subscribe to our email alerts, e-newsletters, and promotional communications, we will use your name and email address to send them to you. Out of respect for your privacy, if you no longer wish to receive our email alerts, e-newsletters, and promotional communications, you can easily opt-out by using the Unsubscribe link included in each communication, reply to the email requesting to be removed from the list, contact us at mailing@habtoorhospitality.com</p><p>We will not retain any of your information thereon on any of our systems, except the log of your request for removal.</p><h2>EU RESIDENTS / GDPR</h2><p>Though made applicable to all, acknowledging to (General Data Protection Regulation) GDPR of the European Union (EU), we emphasise that EU residents have rights to access personal data about them, and to limit use and disclosure of their personal data. We are committed to respect those rights. We acknowledge potential liability in cases of onward transfer of personal data to third parties who do not meet the criteria as set forth in this Policy.</p><p>We use an annual self-assessment to review its compliance with this Policy. Any employee who violates this policy will be subject to discipline, up to and including termination of employment.</p><h2>USER ACCESS AND CHOICE</h2><p>Upon request we will provide you with information about whether we hold any of your personal information. If your information changes, you may correct, update, amend, remove, or ask to have it removed by making the change on your user account settings page, by emailing our Customer Support Team at mailing@habtoorhospitality.com or by contacting us by telephone or postal mail at the contact information listed below. If you no longer desire our Service, please contact us directly.</p><p>We will retain your information for as long as your account is active, as needed to provide you Services and as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements.</p><h2>CONFIDENTIALITY AND SECURITY</h2><p>We warrant that all customer data remains the property of our customers. We also will not rent, sell, transfer, or otherwise expose the contents of the tracking information resulting from click through, message opened, message read, or eCommerce conversions.</p><p>In general, we do not collect data on this website. However, we follow generally accepted standards to protect the information submitted to us, both during transmission and once we receive it. This website www.habtoorhospitality.com provides an SSL encrypted, password-protected mechanism. We seek to use reasonable organizational, technical and administrative measures to protect Personal Information within our organization. Unfortunately, no data transmission or storage system can be guaranteed to be 100% secure.</p><h2>SOCIAL MEDIA FEATURES</h2><p>Our website includes social media features, such as links to our Facebook, YouTube, Google+, Google Blogger, LinkedIn and Twitter pages. These features may collect your IP address, which page you are visiting on our site, and may set a cookie to enable the feature to function properly. Social media features and widgets are either hosted by a third party or hosted directly on our site. Your interactions with these features are governed by the privacy policy of the company providing it.</p><h2>UNSOLICITED COMMERCIAL EMAIL (SPAM)</h2><p>Habtoorhospitality.com is committed to providing a permission-based model for email marketing. To that end, we carry a strict anti-spam policy for all our clients. We have explicitly prohibited our staff from sending any unsolicited material to users who have not expressed their permission to receive communications from them.</p><h2>UPDATES TO THIS PRIVACY STATEMENT</h2><p>We may change this Privacy Statement. The “LAST UPDATED” legend at the top of this page indicates when this Privacy Statement was last revised. Any changes will become effective when we post the revised Privacy Statement on the Online Services. Your use of the Services following these changes means that you accept the revised Privacy Statement. Because email communications are not always secure, please do not include credit card or other sensitive information in your emails to us.</p><h2>YOUR ACCEPTANCE OF THESE TERMS</h2><p>By using this Site, you signify your acceptance of this policy and terms of service. If you do not agree to this policy, please do not use our Site. Your continued use of the Site following the posting of changes to this policy will be deemed your acceptance of those changes.</p><h2>CONTACTING US</h2><p>We have created this privacy policy so that you can understand the care with which we intend to treat your information. To report any abuse or violations, or to contact us with any questions or concerns regarding this privacy policy, please contact us at:</p><p>Al Habtoor Group</p><p>Al Safa 2, Al Wasl Road,</p><p>Dubai,</p><p>United Arab Emirates</p><p>Data Controller: abuse@habtoorhospitality.com</p><p>Phone: +971 4704 8888</p><ul><li class="ql-align-center"><br></li></ul><p><br></p>',
};
const transactionData = [
  {
    name: "Jan",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Feb",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Mar",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Apr",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "May",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Jun",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Jul",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Aug",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Sep",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Oct",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Nov",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
  {
    name: "Dec",
    total: Math.floor(Math.random() * 5000) + 1000,
  },
];

const users = [
  {
    name: "Nevil",
    userId: 2343241,
    email: "nevil@example.com",
    phoneNumber: "123-456-7890",
    isActive: true,
  },
  {
    name: "Alice",
    userId: 9876541,
    email: "alice@example.com",
    phoneNumber: "234-567-8901",
    isActive: false,
  },
  {
    name: "Bob",
    userId: 1234561,
    email: "bob@example.com",
    phoneNumber: "345-678-9012",
    isActive: true,
  },
  {
    name: "Charlie",
    userId: 5678901,
    email: "charlie@example.com",
    phoneNumber: "456-789-0123",
    isActive: false,
  },
  {
    name: "David",
    userId: 3456781,
    email: "david@example.com",
    phoneNumber: "567-890-1234",
    isActive: true,
  },
  {
    name: "Eve",
    userId: 9012341,
    email: "eve@example.com",
    phoneNumber: "678-901-2345",
    isActive: false,
  },
  {
    name: "Frank",
    userId: 7890121,
    email: "frank@example.com",
    phoneNumber: "789-012-3456",
    isActive: true,
  },
  {
    name: "Grace",
    userId: 3456782,
    email: "grace@example.com",
    phoneNumber: "890-123-4567",
    isActive: false,
  },
  {
    name: "Hannah",
    userId: 9012342,
    email: "hannah@example.com",
    phoneNumber: "901-234-5678",
    isActive: true,
  },
  {
    name: "Isaac",
    userId: 782390121,
    email: "isaac@example.com",
    phoneNumber: "012-345-6789",
    isActive: false,
  },
  {
    name: "Jane",
    userId: 2343242,
    email: "jane@example.com",
    phoneNumber: "321-654-9870",
    isActive: true,
  },
  {
    name: "Kevin",
    userId: 9876542,
    email: "kevin@example.com",
    phoneNumber: "432-765-1098",
    isActive: false,
  },
  {
    name: "Lily",
    userId: 1234562,
    email: "lily@example.com",
    phoneNumber: "543-876-2109",
    isActive: true,
  },
  {
    name: "Michael",
    userId: 5678902,
    email: "michael@example.com",
    phoneNumber: "654-987-3210",
    isActive: false,
  },
  {
    name: "Nora",
    userId: 3456783,
    email: "nora@example.com",
    phoneNumber: "765-210-4321",
    isActive: true,
  },
  {
    name: "Oliver",
    userId: 9012343,
    email: "oliver@example.com",
    phoneNumber: "876-543-2109",
    isActive: false,
  },
  {
    name: "Pamela",
    userId: 7890123,
    email: "pamela@example.com",
    phoneNumber: "987-210-5432",
    isActive: true,
  },
  {
    name: "Quinn",
    userId: 3456784,
    email: "quinn@example.com",
    phoneNumber: "098-765-4321",
    isActive: false,
  },
  {
    name: "Rachel",
    userId: 9012344,
    email: "rachel@example.com",
    phoneNumber: "210-543-8765",
    isActive: true,
  },
  {
    name: "Simon",
    userId: 7890124,
    email: "simon@example.com",
    phoneNumber: "321-098-7654",
    isActive: false,
  },
];
const transactions = [
  {
    id: "728ed52f",
    amount: 100,
    status: "pending",
    email: "m@example.com",
    location: "kerala",
  },
  {
    id: "6fbab34d",
    amount: 75,
    status: "completed",
    email: "a@example.com",
    location: "kerala",
  },
  {
    id: "12c5e8a9",
    amount: 120,
    status: "pending",
    email: "b@example.com",
    location: "kerala",
  },
  {
    id: "9cfa2d3e",
    amount: 50,
    status: "completed",
    email: "c@example.com",
    location: "kerala",
  },
  {
    id: "5d8f7b2c",
    amount: 200,
    status: "pending",
    email: "d@example.com",
    location: "kerala",
  },
  {
    id: "2a1e3c4b",
    amount: 150,
    status: "completed",
    email: "e@example.com",
    location: "kerala",
  },
  {
    id: "8f6a9d1b",
    amount: 90,
    status: "pending",
    email: "f@example.com",
    location: "kerala",
  },
  {
    id: "3e2b1c5d",
    amount: 80,
    status: "completed",
    email: "g@example.com",
    location: "kerala",
  },
  {
    id: "7d6e8f2a",
    amount: 110,
    status: "pending",
    email: "h@example.com",
    location: "kerala",
  },
  {
    id: "4b5c1d2e",
    amount: 70,
    status: "completed",
    email: "i@example.com",
    location: "kerala",
  },
  {
    id: "1c3b2a4d",
    amount: 130,
    status: "pending",
    email: "j@example.com",
    location: "kerala",
  },
  {
    id: "5e8d4c7f",
    amount: 85,
    status: "completed",
    email: "k@example.com",
    location: "kerala",
  },
  {
    id: "9a2b4c8e",
    amount: 95,
    status: "pending",
    email: "l@example.com",
    location: "kerala",
  },
  {
    id: "6f2d1c9a",
    amount: 180,
    status: "completed",
    email: "n@example.com",
    location: "kerala",
  },
  {
    id: "3b1a5c7d",
    amount: 60,
    status: "pending",
    email: "o@example.com",
    location: "kerala",
  },
  {
    id: "8e2a4b1d",
    amount: 140,
    status: "completed",
    email: "p@example.com",
    location: "kerala",
  },
  {
    id: "2c1d3e5b",
    amount: 170,
    status: "pending",
    email: "q@example.com",
    location: "kerala",
  },
  {
    id: "7f5c4d1e",
    amount: 65,
    status: "completed",
    email: "r@example.com",
    location: "kerala",
  },
  {
    id: "4a2b1c3d",
    amount: 125,
    status: "pending",
    email: "s@example.com",
    location: "kerala",
  },
  {
    id: "1e3d2b4c",
    amount: 155,
    status: "completed",
    email: "t@example.com",
    location: "kerala",
  },
  {
    id: "9c7d5e3b",
    amount: 105,
    status: "pending",
    email: "u@example.com",
    location: "kerala",
  },
  {
    id: "6a8b1d2c",
    amount: 145,
    status: "completed",
    email: "v@example.com",
    location: "kerala",
  },
  {
    id: "3f2e4c1b",
    amount: 175,
    status: "pending",
    email: "w@example.com",
    location: "kerala",
  },
  {
    id: "8d1c2b5e",
    amount: 55,
    status: "completed",
    email: "x@example.com",
    location: "kerala",
  },
  {
    id: "5b3e2d4f",
    amount: 135,
    status: "pending",
    email: "y@example.com",
    location: "kerala",
  },
  {
    id: "2c4d5e3a",
    amount: 160,
    status: "completed",
    email: "z@example.com",
    location: "kerala",
  },
  {
    id: "7b1d3c5e",
    amount: 115,
    status: "pending",
    email: "aa@example.com",
    location: "kerala",
  },
  {
    id: "4e5d1b2c",
    amount: 45,
    status: "completed",
    email: "ab@example.com",
    location: "kerala",
  },
  {
    id: "1f3d5b2e",
    amount: 165,
    status: "pending",
    email: "ac@example.com",
    location: "kerala",
  },
  {
    id: "9a8c5e3b",
    amount: 75,
    status: "completed",
    email: "ad@example.com",
    location: "kerala",
  },
  {
    id: "6d4e3c1b",
    amount: 195,
    status: "pending",
    email: "ae@example.com",
    location: "kerala",
  },
  {
    id: "3a1b5c2d",
    amount: 40,
    status: "completed",
    email: "af@example.com",
    location: "kerala",
  },
  {
    id: "8d7e4a2b",
    amount: 150,
    status: "pending",
    email: "ag@example.com",
    location: "kerala",
  },
  {
    id: "5e3c2d1b",
    amount: 185,
    status: "completed",
    email: "ah@example.com",
    location: "kerala",
  },
  {
    id: "2a4b3d5c",
    amount: 35,
    status: "pending",
    email: "ai@example.com",
    location: "kerala",
  },
  {
    id: "7d5e2c4b",
    amount: 170,
    status: "completed",
    email: "aj@example.com",
    location: "kerala",
  },
  {
    id: "4b1a3c2d",
    amount: 195,
    status: "pending",
    email: "ak@example.com",
    location: "kerala",
  },
  {
    id: "1e5d2c4b",
    amount: 30,
    status: "completed",
    email: "al@example.com",
    location: "kerala",
  },
  {
    id: "9a7c3e5d",
    amount: 175,
    status: "pending",
    email: "am@example.com",
    location: "kerala",
  },
  {
    id: "6b4c1d3e",
    amount: 25,
    status: "completed",
    email: "an@example.com",
    location: "kerala",
  },
  {
    id: "3d5e1b4c",
    amount: 190,
    status: "pending",
    email: "ao@example.com",
    location: "kerala",
  },
  {
    id: "8a7b5c2d",
    amount: 20,
    status: "completed",
    email: "ap@example.com",
    location: "kerala",
  },
  {
    id: "5e3d2b4c",
    amount: 165,
    status: "pending",
    email: "aq@example.com",
    location: "kerala",
  },
  {
    id: "2a4b1d3c",
    amount: 195,
    status: "completed",
    email: "ar@example.com",
    location: "kerala",
  },
  {
    id: "7c5e3d1b",
    amount: 15,
    status: "pending",
    email: "as@example.com",
    location: "kerala",
  },
  {
    id: "4d2b5c1e",
    amount: 160,
    status: "completed",
    email: "at@example.com",
    location: "kerala",
  },
  {
    id: "1c3d5b4e",
    amount: 10,
    status: "pending",
    email: "au@example.com",
    location: "kerala",
  },
  {
    id: "9a5d2b3c",
    amount: 155,
    status: "completed",
    email: "av@example.com",
    location: "kerala",
  },
  {
    id: "6c4d3e2b",
    amount: 195,
    status: "pending",
    email: "aw@example.com",
    location: "kerala",
  },
  {
    id: "3e1b5c4d",
    amount: 5,
    status: "completed",
    email: "ax@example.com",
    location: "kerala",
  },
  {
    id: "8d2b3c5e",
    amount: 150,
    status: "pending",
    email: "ay@example.com",
    location: "kerala",
  },
  {
    id: "5a3b1d2c",
    amount: 195,
    status: "completed",
    email: "az@example.com",
    location: "kerala",
  },
  {
    id: "2e4d5c3b",
    amount: 0,
    status: "pending",
    email: "ba@example.com",
    location: "kerala",
  },
];

const countryCodes = [
  {
    name: "Afghanistan",
    dial_code: "+93",
    code: "AF",
  },
  {
    name: "Aland Islands",
    dial_code: "+358",
    code: "AX",
  },
  {
    name: "Albania",
    dial_code: "+355",
    code: "AL",
  },
  {
    name: "Algeria",
    dial_code: "+213",
    code: "DZ",
  },
  {
    name: "AmericanSamoa",
    dial_code: "+1684",
    code: "AS",
  },
  {
    name: "Andorra",
    dial_code: "+376",
    code: "AD",
  },
  {
    name: "Angola",
    dial_code: "+244",
    code: "AO",
  },
  {
    name: "Anguilla",
    dial_code: "+1264",
    code: "AI",
  },
  {
    name: "Antarctica",
    dial_code: "+672",
    code: "AQ",
  },
  {
    name: "Antigua and Barbuda",
    dial_code: "+1268",
    code: "AG",
  },
  {
    name: "Argentina",
    dial_code: "+54",
    code: "AR",
  },
  {
    name: "Armenia",
    dial_code: "+374",
    code: "AM",
  },
  {
    name: "Aruba",
    dial_code: "+297",
    code: "AW",
  },
  {
    name: "Australia",
    dial_code: "+61",
    code: "AU",
  },
  {
    name: "Austria",
    dial_code: "+43",
    code: "AT",
  },
  {
    name: "Azerbaijan",
    dial_code: "+994",
    code: "AZ",
  },
  {
    name: "Bahamas",
    dial_code: "+1242",
    code: "BS",
  },
  {
    name: "Bahrain",
    dial_code: "+973",
    code: "BH",
  },
  {
    name: "Bangladesh",
    dial_code: "+880",
    code: "BD",
  },
  {
    name: "Barbados",
    dial_code: "+1246",
    code: "BB",
  },
  {
    name: "Belarus",
    dial_code: "+375",
    code: "BY",
  },
  {
    name: "Belgium",
    dial_code: "+32",
    code: "BE",
  },
  {
    name: "Belize",
    dial_code: "+501",
    code: "BZ",
  },
  {
    name: "Benin",
    dial_code: "+229",
    code: "BJ",
  },
  {
    name: "Bermuda",
    dial_code: "+1441",
    code: "BM",
  },
  {
    name: "Bhutan",
    dial_code: "+975",
    code: "BT",
  },
  {
    name: "Bolivia, Plurinational State of",
    dial_code: "+591",
    code: "BO",
  },
  {
    name: "Bosnia and Herzegovina",
    dial_code: "+387",
    code: "BA",
  },
  {
    name: "Botswana",
    dial_code: "+267",
    code: "BW",
  },
  {
    name: "Brazil",
    dial_code: "+55",
    code: "BR",
  },
  {
    name: "British Indian Ocean Territory",
    dial_code: "+246",
    code: "IO",
  },
  {
    name: "Brunei Darussalam",
    dial_code: "+673",
    code: "BN",
  },
  {
    name: "Bulgaria",
    dial_code: "+359",
    code: "BG",
  },
  {
    name: "Burkina Faso",
    dial_code: "+226",
    code: "BF",
  },
  {
    name: "Burundi",
    dial_code: "+257",
    code: "BI",
  },
  {
    name: "Cambodia",
    dial_code: "+855",
    code: "KH",
  },
  {
    name: "Cameroon",
    dial_code: "+237",
    code: "CM",
  },
  {
    name: "Canada",
    dial_code: "+1",
    code: "CA",
  },
  {
    name: "Cape Verde",
    dial_code: "+238",
    code: "CV",
  },
  {
    name: "Cayman Islands",
    dial_code: "+ 345",
    code: "KY",
  },
  {
    name: "Central African Republic",
    dial_code: "+236",
    code: "CF",
  },
  {
    name: "Chad",
    dial_code: "+235",
    code: "TD",
  },
  {
    name: "Chile",
    dial_code: "+56",
    code: "CL",
  },
  {
    name: "China",
    dial_code: "+86",
    code: "CN",
  },
  {
    name: "Christmas Island",
    dial_code: "+61",
    code: "CX",
  },
  {
    name: "Cocos (Keeling) Islands",
    dial_code: "+61",
    code: "CC",
  },
  {
    name: "Colombia",
    dial_code: "+57",
    code: "CO",
  },
  {
    name: "Comoros",
    dial_code: "+269",
    code: "KM",
  },
  {
    name: "Congo",
    dial_code: "+242",
    code: "CG",
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    dial_code: "+243",
    code: "CD",
  },
  {
    name: "Cook Islands",
    dial_code: "+682",
    code: "CK",
  },
  {
    name: "Costa Rica",
    dial_code: "+506",
    code: "CR",
  },
  {
    name: "Cote d'Ivoire",
    dial_code: "+225",
    code: "CI",
  },
  {
    name: "Croatia",
    dial_code: "+385",
    code: "HR",
  },
  {
    name: "Cuba",
    dial_code: "+53",
    code: "CU",
  },
  {
    name: "Cyprus",
    dial_code: "+357",
    code: "CY",
  },
  {
    name: "Czech Republic",
    dial_code: "+420",
    code: "CZ",
  },
  {
    name: "Denmark",
    dial_code: "+45",
    code: "DK",
  },
  {
    name: "Djibouti",
    dial_code: "+253",
    code: "DJ",
  },
  {
    name: "Dominica",
    dial_code: "+1767",
    code: "DM",
  },
  {
    name: "Dominican Republic",
    dial_code: "+1849",
    code: "DO",
  },
  {
    name: "Ecuador",
    dial_code: "+593",
    code: "EC",
  },
  {
    name: "Egypt",
    dial_code: "+20",
    code: "EG",
  },
  {
    name: "El Salvador",
    dial_code: "+503",
    code: "SV",
  },
  {
    name: "Equatorial Guinea",
    dial_code: "+240",
    code: "GQ",
  },
  {
    name: "Eritrea",
    dial_code: "+291",
    code: "ER",
  },
  {
    name: "Estonia",
    dial_code: "+372",
    code: "EE",
  },
  {
    name: "Ethiopia",
    dial_code: "+251",
    code: "ET",
  },
  {
    name: "Falkland Islands (Malvinas)",
    dial_code: "+500",
    code: "FK",
  },
  {
    name: "Faroe Islands",
    dial_code: "+298",
    code: "FO",
  },
  {
    name: "Fiji",
    dial_code: "+679",
    code: "FJ",
  },
  {
    name: "Finland",
    dial_code: "+358",
    code: "FI",
  },
  {
    name: "France",
    dial_code: "+33",
    code: "FR",
  },
  {
    name: "French Guiana",
    dial_code: "+594",
    code: "GF",
  },
  {
    name: "French Polynesia",
    dial_code: "+689",
    code: "PF",
  },
  {
    name: "Gabon",
    dial_code: "+241",
    code: "GA",
  },
  {
    name: "Gambia",
    dial_code: "+220",
    code: "GM",
  },
  {
    name: "Georgia",
    dial_code: "+995",
    code: "GE",
  },
  {
    name: "Germany",
    dial_code: "+49",
    code: "DE",
  },
  {
    name: "Ghana",
    dial_code: "+233",
    code: "GH",
  },
  {
    name: "Gibraltar",
    dial_code: "+350",
    code: "GI",
  },
  {
    name: "Greece",
    dial_code: "+30",
    code: "GR",
  },
  {
    name: "Greenland",
    dial_code: "+299",
    code: "GL",
  },
  {
    name: "Grenada",
    dial_code: "+1473",
    code: "GD",
  },
  {
    name: "Guadeloupe",
    dial_code: "+590",
    code: "GP",
  },
  {
    name: "Guam",
    dial_code: "+1671",
    code: "GU",
  },
  {
    name: "Guatemala",
    dial_code: "+502",
    code: "GT",
  },
  {
    name: "Guernsey",
    dial_code: "+44",
    code: "GG",
  },
  {
    name: "Guinea",
    dial_code: "+224",
    code: "GN",
  },
  {
    name: "Guinea-Bissau",
    dial_code: "+245",
    code: "GW",
  },
  {
    name: "Guyana",
    dial_code: "+595",
    code: "GY",
  },
  {
    name: "Haiti",
    dial_code: "+509",
    code: "HT",
  },
  {
    name: "Holy See (Vatican City State)",
    dial_code: "+379",
    code: "VA",
  },
  {
    name: "Honduras",
    dial_code: "+504",
    code: "HN",
  },
  {
    name: "Hong Kong",
    dial_code: "+852",
    code: "HK",
  },
  {
    name: "Hungary",
    dial_code: "+36",
    code: "HU",
  },
  {
    name: "Iceland",
    dial_code: "+354",
    code: "IS",
  },
  {
    name: "India",
    dial_code: "+91",
    code: "IN",
  },
  {
    name: "Indonesia",
    dial_code: "+62",
    code: "ID",
  },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    dial_code: "+98",
    code: "IR",
  },
  {
    name: "Iraq",
    dial_code: "+964",
    code: "IQ",
  },
  {
    name: "Ireland",
    dial_code: "+353",
    code: "IE",
  },
  {
    name: "Isle of Man",
    dial_code: "+44",
    code: "IM",
  },
  {
    name: "Israel",
    dial_code: "+972",
    code: "IL",
  },
  {
    name: "Italy",
    dial_code: "+39",
    code: "IT",
  },
  {
    name: "Jamaica",
    dial_code: "+1876",
    code: "JM",
  },
  {
    name: "Japan",
    dial_code: "+81",
    code: "JP",
  },
  {
    name: "Jersey",
    dial_code: "+44",
    code: "JE",
  },
  {
    name: "Jordan",
    dial_code: "+962",
    code: "JO",
  },
  {
    name: "Kazakhstan",
    dial_code: "+77",
    code: "KZ",
  },
  {
    name: "Kenya",
    dial_code: "+254",
    code: "KE",
  },
  {
    name: "Kiribati",
    dial_code: "+686",
    code: "KI",
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dial_code: "+850",
    code: "KP",
  },
  {
    name: "Korea, Republic of South Korea",
    dial_code: "+82",
    code: "KR",
  },
  {
    name: "Kuwait",
    dial_code: "+965",
    code: "KW",
  },
  {
    name: "Kyrgyzstan",
    dial_code: "+996",
    code: "KG",
  },
  {
    name: "Laos",
    dial_code: "+856",
    code: "LA",
  },
  {
    name: "Latvia",
    dial_code: "+371",
    code: "LV",
  },
  {
    name: "Lebanon",
    dial_code: "+961",
    code: "LB",
  },
  {
    name: "Lesotho",
    dial_code: "+266",
    code: "LS",
  },
  {
    name: "Liberia",
    dial_code: "+231",
    code: "LR",
  },
  {
    name: "Libyan Arab Jamahiriya",
    dial_code: "+218",
    code: "LY",
  },
  {
    name: "Liechtenstein",
    dial_code: "+423",
    code: "LI",
  },
  {
    name: "Lithuania",
    dial_code: "+370",
    code: "LT",
  },
  {
    name: "Luxembourg",
    dial_code: "+352",
    code: "LU",
  },
  {
    name: "Macao",
    dial_code: "+853",
    code: "MO",
  },
  {
    name: "Macedonia",
    dial_code: "+389",
    code: "MK",
  },
  {
    name: "Madagascar",
    dial_code: "+261",
    code: "MG",
  },
  {
    name: "Malawi",
    dial_code: "+265",
    code: "MW",
  },
  {
    name: "Malaysia",
    dial_code: "+60",
    code: "MY",
  },
  {
    name: "Maldives",
    dial_code: "+960",
    code: "MV",
  },
  {
    name: "Mali",
    dial_code: "+223",
    code: "ML",
  },
  {
    name: "Malta",
    dial_code: "+356",
    code: "MT",
  },
  {
    name: "Marshall Islands",
    dial_code: "+692",
    code: "MH",
  },
  {
    name: "Martinique",
    dial_code: "+596",
    code: "MQ",
  },
  {
    name: "Mauritania",
    dial_code: "+222",
    code: "MR",
  },
  {
    name: "Mauritius",
    dial_code: "+230",
    code: "MU",
  },
  {
    name: "Mayotte",
    dial_code: "+262",
    code: "YT",
  },
  {
    name: "Mexico",
    dial_code: "+52",
    code: "MX",
  },
  {
    name: "Micronesia, Federated States of Micronesia",
    dial_code: "+691",
    code: "FM",
  },
  {
    name: "Moldova",
    dial_code: "+373",
    code: "MD",
  },
  {
    name: "Monaco",
    dial_code: "+377",
    code: "MC",
  },
  {
    name: "Mongolia",
    dial_code: "+976",
    code: "MN",
  },
  {
    name: "Montenegro",
    dial_code: "+382",
    code: "ME",
  },
  {
    name: "Montserrat",
    dial_code: "+1664",
    code: "MS",
  },
  {
    name: "Morocco",
    dial_code: "+212",
    code: "MA",
  },
  {
    name: "Mozambique",
    dial_code: "+258",
    code: "MZ",
  },
  {
    name: "Myanmar",
    dial_code: "+95",
    code: "MM",
  },
  {
    name: "Namibia",
    dial_code: "+264",
    code: "NA",
  },
  {
    name: "Nauru",
    dial_code: "+674",
    code: "NR",
  },
  {
    name: "Nepal",
    dial_code: "+977",
    code: "NP",
  },
  {
    name: "Netherlands",
    dial_code: "+31",
    code: "NL",
  },
  {
    name: "Netherlands Antilles",
    dial_code: "+599",
    code: "AN",
  },
  {
    name: "New Caledonia",
    dial_code: "+687",
    code: "NC",
  },
  {
    name: "New Zealand",
    dial_code: "+64",
    code: "NZ",
  },
  {
    name: "Nicaragua",
    dial_code: "+505",
    code: "NI",
  },
  {
    name: "Niger",
    dial_code: "+227",
    code: "NE",
  },
  {
    name: "Nigeria",
    dial_code: "+234",
    code: "NG",
  },
  {
    name: "Niue",
    dial_code: "+683",
    code: "NU",
  },
  {
    name: "Norfolk Island",
    dial_code: "+672",
    code: "NF",
  },
  {
    name: "Northern Mariana Islands",
    dial_code: "+1670",
    code: "MP",
  },
  {
    name: "Norway",
    dial_code: "+47",
    code: "NO",
  },
  {
    name: "Oman",
    dial_code: "+968",
    code: "OM",
  },
  {
    name: "Pakistan",
    dial_code: "+92",
    code: "PK",
  },
  {
    name: "Palau",
    dial_code: "+680",
    code: "PW",
  },
  {
    name: "Palestinian Territory, Occupied",
    dial_code: "+970",
    code: "PS",
  },
  {
    name: "Panama",
    dial_code: "+507",
    code: "PA",
  },
  {
    name: "Papua New Guinea",
    dial_code: "+675",
    code: "PG",
  },
  {
    name: "Paraguay",
    dial_code: "+595",
    code: "PY",
  },
  {
    name: "Peru",
    dial_code: "+51",
    code: "PE",
  },
  {
    name: "Philippines",
    dial_code: "+63",
    code: "PH",
  },
  {
    name: "Pitcairn",
    dial_code: "+872",
    code: "PN",
  },
  {
    name: "Poland",
    dial_code: "+48",
    code: "PL",
  },
  {
    name: "Portugal",
    dial_code: "+351",
    code: "PT",
  },
  {
    name: "Puerto Rico",
    dial_code: "+1939",
    code: "PR",
  },
  {
    name: "Qatar",
    dial_code: "+974",
    code: "QA",
  },
  {
    name: "Romania",
    dial_code: "+40",
    code: "RO",
  },
  {
    name: "Russia",
    dial_code: "+7",
    code: "RU",
  },
  {
    name: "Rwanda",
    dial_code: "+250",
    code: "RW",
  },
  {
    name: "Reunion",
    dial_code: "+262",
    code: "RE",
  },
  {
    name: "Saint Barthelemy",
    dial_code: "+590",
    code: "BL",
  },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    dial_code: "+290",
    code: "SH",
  },
  {
    name: "Saint Kitts and Nevis",
    dial_code: "+1869",
    code: "KN",
  },
  {
    name: "Saint Lucia",
    dial_code: "+1758",
    code: "LC",
  },
  {
    name: "Saint Martin",
    dial_code: "+590",
    code: "MF",
  },
  {
    name: "Saint Pierre and Miquelon",
    dial_code: "+508",
    code: "PM",
  },
  {
    name: "Saint Vincent and the Grenadines",
    dial_code: "+1784",
    code: "VC",
  },
  {
    name: "Samoa",
    dial_code: "+685",
    code: "WS",
  },
  {
    name: "San Marino",
    dial_code: "+378",
    code: "SM",
  },
  {
    name: "Sao Tome and Principe",
    dial_code: "+239",
    code: "ST",
  },
  {
    name: "Saudi Arabia",
    dial_code: "+966",
    code: "SA",
  },
  {
    name: "Senegal",
    dial_code: "+221",
    code: "SN",
  },
  {
    name: "Serbia",
    dial_code: "+381",
    code: "RS",
  },
  {
    name: "Seychelles",
    dial_code: "+248",
    code: "SC",
  },
  {
    name: "Sierra Leone",
    dial_code: "+232",
    code: "SL",
  },
  {
    name: "Singapore",
    dial_code: "+65",
    code: "SG",
  },
  {
    name: "Slovakia",
    dial_code: "+421",
    code: "SK",
  },
  {
    name: "Slovenia",
    dial_code: "+386",
    code: "SI",
  },
  {
    name: "Solomon Islands",
    dial_code: "+677",
    code: "SB",
  },
  {
    name: "Somalia",
    dial_code: "+252",
    code: "SO",
  },
  {
    name: "South Africa",
    dial_code: "+27",
    code: "ZA",
  },
  {
    name: "South Sudan",
    dial_code: "+211",
    code: "SS",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    dial_code: "+500",
    code: "GS",
  },
  {
    name: "Spain",
    dial_code: "+34",
    code: "ES",
  },
  {
    name: "Sri Lanka",
    dial_code: "+94",
    code: "LK",
  },
  {
    name: "Sudan",
    dial_code: "+249",
    code: "SD",
  },
  {
    name: "Suriname",
    dial_code: "+597",
    code: "SR",
  },
  {
    name: "Svalbard and Jan Mayen",
    dial_code: "+47",
    code: "SJ",
  },
  {
    name: "Swaziland",
    dial_code: "+268",
    code: "SZ",
  },
  {
    name: "Sweden",
    dial_code: "+46",
    code: "SE",
  },
  {
    name: "Switzerland",
    dial_code: "+41",
    code: "CH",
  },
  {
    name: "Syrian Arab Republic",
    dial_code: "+963",
    code: "SY",
  },
  {
    name: "Taiwan",
    dial_code: "+886",
    code: "TW",
  },
  {
    name: "Tajikistan",
    dial_code: "+992",
    code: "TJ",
  },
  {
    name: "Tanzania, United Republic of Tanzania",
    dial_code: "+255",
    code: "TZ",
  },
  {
    name: "Thailand",
    dial_code: "+66",
    code: "TH",
  },
  {
    name: "Timor-Leste",
    dial_code: "+670",
    code: "TL",
  },
  {
    name: "Togo",
    dial_code: "+228",
    code: "TG",
  },
  {
    name: "Tokelau",
    dial_code: "+690",
    code: "TK",
  },
  {
    name: "Tonga",
    dial_code: "+676",
    code: "TO",
  },
  {
    name: "Trinidad and Tobago",
    dial_code: "+1868",
    code: "TT",
  },
  {
    name: "Tunisia",
    dial_code: "+216",
    code: "TN",
  },
  {
    name: "Turkey",
    dial_code: "+90",
    code: "TR",
  },
  {
    name: "Turkmenistan",
    dial_code: "+993",
    code: "TM",
  },
  {
    name: "Turks and Caicos Islands",
    dial_code: "+1649",
    code: "TC",
  },
  {
    name: "Tuvalu",
    dial_code: "+688",
    code: "TV",
  },
  {
    name: "Uganda",
    dial_code: "+256",
    code: "UG",
  },
  {
    name: "Ukraine",
    dial_code: "+380",
    code: "UA",
  },
  {
    name: "United Arab Emirates",
    dial_code: "+971",
    code: "AE",
  },
  {
    name: "United Kingdom",
    dial_code: "+44",
    code: "GB",
  },
  {
    name: "United States",
    dial_code: "+1",
    code: "US",
  },
  {
    name: "Uruguay",
    dial_code: "+598",
    code: "UY",
  },
  {
    name: "Uzbekistan",
    dial_code: "+998",
    code: "UZ",
  },
  {
    name: "Vanuatu",
    dial_code: "+678",
    code: "VU",
  },
  {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    dial_code: "+58",
    code: "VE",
  },
  {
    name: "Vietnam",
    dial_code: "+84",
    code: "VN",
  },
  {
    name: "Virgin Islands, British",
    dial_code: "+1284",
    code: "VG",
  },
  {
    name: "Virgin Islands, U.S.",
    dial_code: "+1340",
    code: "VI",
  },
  {
    name: "Wallis and Futuna",
    dial_code: "+681",
    code: "WF",
  },
  {
    name: "Yemen",
    dial_code: "+967",
    code: "YE",
  },
  {
    name: "Zambia",
    dial_code: "+260",
    code: "ZM",
  },
  {
    name: "Zimbabwe",
    dial_code: "+263",
    code: "ZW",
  },
];

const guestNames = [
  {
    value: "Elisa",
    label: "Elisa",
  },
  {
    value: "Emma",
    label: "Emma",
  },
  {
    value: "Liam",
    label: "Liam",
  },
  {
    value: "Olivia",
    label: "Olivia",
  },
  {
    value: "Noah",
    label: "Noah",
  },
  {
    value: "Ava",
    label: "Ava",
  },
  {
    value: "William",
    label: "William",
  },
  {
    value: "Sophia",
    label: "Sophia",
  },
  {
    value: "James",
    label: "James",
  },
  {
    value: "Isabella",
    label: "Isabella",
  },
];

const guestTransactionDetails = [
  {
    sno: 1,
    name: "Rohit Sharma",
    transactionNo: "TRX20240503001",
    date: "2024-05-03",
    time: "2:45 PM",
    location: "Kerala",
    transactionValue: "Kerala",
    pointsEarned: "+432",
  },
  {
    sno: 2,
    name: "Aswin",
    transactionNo: "TRX20240503009",
    date: "2024-05-05",
    time: "2:45 PM",
    location: "Kerala",
    transactionValue: "20400",
    pointsEarned: "+532",
  },
  {
    sno: 3,
    name: "Nikhil",
    transactionNo: "TRX20240503007",
    date: "2024-02-03",
    time: "2:45 PM",
    location: "Kerala",
    transactionValue: "100000",
    pointsEarned: "+832",
  },
  {
    sno: 4,
    name: "Nevil Krishna",
    transactionNo: "TRX20240503002",
    date: "2024-05-04",
    time: "2:54 PM",
    location: "Kerala",
    transactionValue: "8070",
    pointsEarned: "+232",
  },
  {
    sno: 5,
    name: "Arun Shankaran",
    transactionNo: "TRX20240503001",
    date: "2024-07-03",
    time: "1:45 PM",
    location: "Kerala",
    transactionValue: "3000",
    pointsEarned: "+132",
  },
  {
    sno: 6,
    name: "Roberto",
    transactionNo: "TRX20240503012",
    date: "2024-03-03",
    time: "1:43 PM",
    location: "Dubai",
    transactionValue: "31000",
    pointsEarned: "+1232",
  },
  {
    sno: 7,
    name: "Ajmal",
    transactionNo: "TRX20240503031",
    date: "2024-07-07",
    time: "4:45 PM",
    location: "Saudi",
    transactionValue: "13000",
    pointsEarned: "+732",
  },
  {
    sno: 8,
    name: "Anand",
    transactionNo: "TRX20240503021",
    date: "2024-08-07",
    time: "6:45 PM",
    location: "india",
    transactionValue: "23000",
    pointsEarned: "+932",
  },
  {
    sno: 9,
    name: "Ajith",
    transactionNo: "TRX20240503121",
    date: "2024-10-07",
    time: "7:45 PM",
    location: "Kerala",
    transactionValue: "43000",
    pointsEarned: "+1932",
  },
  {
    sno: 10,
    name: "Surjith",
    transactionNo: "TRX20240503101",
    date: "2024-10-09",
    time: "9:45 AM",
    location: "Saudi",
    transactionValue: "16000",
    pointsEarned: "+1332",
  },
];

const profileData = [
  { label: "First Name", value: "Arun" },
  { label: "Last Name", value: "Sankaran" },
  { label: "Date of Birth", value: "01 / 01 / 1990" },
  { label: "Phone Number", value: "0123456789" },
  { label: "Email ID", value: "arun@test.com" },
  { label: "Address 1", value: "Address 1" },
  { label: "Address 2", value: "PO Box No. 1" },
  { label: "City", value: "Dubai" },
  { label: "Country", value: "United Arab Emirates" },
  { label: "Loyalty ID", value: "24q32423423422" },
];
const offers = [
  {
    id: 1,
    name: "Offer 1",
    offer_price: 25.99,
    original_price: 39.99,
    location: "New York",
    discount_percentage: 35,
  },
  {
    id: 2,
    name: "Offer 2",
    offer_price: 49.99,
    original_price: 69.99,
    location: "Los Angeles",
    discount_percentage: 28,
  },
  {
    id: 3,
    name: "Offer 3",
    offer_price: 19.99,
    original_price: 29.99,
    location: "Chicago",
    discount_percentage: 33,
  },
  {
    id: 4,
    name: "Offer 4",
    offer_price: 34.99,
    original_price: 49.99,
    location: "Miami",
    discount_percentage: 30,
  },
  {
    id: 5,
    name: "Offer 5",
    offer_price: 59.99,
    original_price: 89.99,
    location: "San Francisco",
    discount_percentage: 33,
  },
  {
    id: 6,
    name: "Offer 6",
    offer_price: 14.99,
    original_price: 24.99,
    location: "Seattle",
    discount_percentage: 40,
  },
  {
    id: 7,
    name: "Offer 7",
    offer_price: 39.99,
    original_price: 59.99,
    location: "Boston",
    discount_percentage: 33,
  },
  {
    id: 8,
    name: "Offer 8",
    offer_price: 45.99,
    original_price: 69.99,
    location: "Dallas",
    discount_percentage: 34,
  },
  {
    id: 9,
    name: "Offer 9",
    offer_price: 22.99,
    original_price: 34.99,
    location: "Denver",
    discount_percentage: 34,
  },
  {
    id: 10,
    name: "Offer 10",
    offer_price: 17.99,
    original_price: 29.99,
    location: "Phoenix",
    discount_percentage: 40,
  },
];
const news = [
  {
    newsId: 1,
    title: "Breaking News 1",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus nec lacinia massa, et tempor libero.",
    date: "2024-05-04",
  },
  {
    newsId: 2,
    title: "Breaking News 2",
    content:
      "Praesent ullamcorper nunc vitae felis dapibus, nec sagittis libero ullamcorper.",
    date: "2024-05-03",
  },
  {
    newsId: 3,
    title: "Breaking News 3",
    content:
      "Fusce id efficitur leo. Donec eleifend massa vel nunc ultricies, nec fringilla dui fermentum.",
    date: "2024-05-02",
  },
  {
    newsId: 4,
    title: "Breaking News 4",
    content:
      "Cras tincidunt semper ex, non scelerisque quam vehicula ut. Ut rutrum neque eu orci gravida, vel rutrum mauris faucibus.",
    date: "2024-05-01",
  },
  {
    newsId: 5,
    title: "Breaking News 5",
    content:
      "Sed vitae felis at purus convallis convallis ut et neque. Duis id felis sed nunc fermentum condimentum.",
    date: "2024-04-30",
  },
  {
    newsId: 6,
    title: "Breaking News 6",
    content:
      "Nulla vitae ultrices tortor, vitae aliquet magna. Aliquam erat volutpat. Phasellus nec vestibulum ligula.",
    date: "2024-04-29",
  },
  {
    newsId: 7,
    title: "Breaking News 7",
    content:
      "Vestibulum ornare magna eu felis scelerisque faucibus. Donec lacinia varius lacus, eu cursus nunc maximus et.",
    date: "2024-04-28",
  },
  {
    newsId: 8,
    title: "Breaking News 8",
    content:
      "Maecenas aliquet vestibulum felis, id iaculis libero aliquam eu. Sed tincidunt enim id fermentum fermentum.",
    date: "2024-04-27",
  },
  {
    newsId: 9,
    title: "Breaking News 9",
    content:
      "Morbi malesuada arcu id malesuada auctor. Curabitur finibus arcu non dolor convallis, sed dapibus risus fermentum.",
    date: "2024-04-26",
  },
  {
    newsId: 10,
    title: "Breaking News 10",
    content:
      "Suspendisse ut sapien nec nulla dignissim gravida. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    date: "2024-04-25",
  },
];
const templates = [
  {
    id: 1,
    templateTitle: "Birthday Wishes",
    templateName: "Happy Birthday to You!",
    content:
      "Wishing you a day filled with love, laughter, and joy. Happy Birthday!",
  },
  {
    id: 2,
    templateTitle: "Birthday Greetings",
    templateName: "Another Year Older",
    content:
      "Cheers to another trip around the sun! May your birthday be as amazing as you are.",
  },
  {
    id: 3,
    templateTitle: "Birthday Celebration",
    templateName: "Let's Party!",
    content:
      "It's time to celebrate! Wishing you a fantastic birthday filled with fun and excitement.",
  },
  {
    id: 4,
    templateTitle: "Birthday Blessings",
    templateName: "Blessings on Your Special Day",
    content:
      "May this birthday bring you abundant happiness and blessings. Enjoy your special day!",
  },
  {
    id: 5,
    templateTitle: "Birthday Joy",
    templateName: "Wishing You Joy and Laughter",
    content:
      "Sending you lots of joy and laughter on your birthday. Have a blast!",
  },
  {
    id: 6,
    templateTitle: "Birthday Fun",
    templateName: "Let's Have Some Fun!",
    content:
      "Birthdays are for making memories and having fun. Let's make this one unforgettable!",
  },
  {
    id: 7,
    templateTitle: "Birthday Adventure",
    templateName: "Embark on an Adventure",
    content:
      "It's your special day, so let's embark on an adventure together! Wishing you excitement and joy.",
  },
  {
    id: 8,
    templateTitle: "Birthday Dreams",
    templateName: "Dream Big on Your Birthday",
    content:
      "On your birthday, dream big and reach for the stars. May all your dreams come true!",
  },
  {
    id: 9,
    templateTitle: "Birthday Magic",
    templateName: "A Touch of Birthday Magic",
    content:
      "May your birthday be filled with magic and wonder, just like you! Enjoy every moment.",
  },
  {
    id: 10,
    templateTitle: "Birthday Cheers",
    templateName: "Cheers to You!",
    content:
      "Raising a toast to you on your birthday! May this year be filled with happiness and success.",
  },
];
// 1. Fix Sort order in Partners. List in order (Hotels; Dining; Entertainment; Leisure; Spa, Pool & Beach; Retail; More Partners)
const propertyTypes = [
  { value: "Hotels", label: "Hotels" },
  { value: "Dining", label: "Dining" },
  {
    value: "Winter Garden And Polo Club",
    label: "Winter Garden And Polo Club",
  },
  { value: "Entertainment", label: "Entertainment" },
  { value: "Leisures", label: "Leisures" },
  { value: "Spa, Pool & Beach", label: "Spa, Pool & Beach" },
  { value: "Retail", label: "Retail" },
  { value: "More Partners", label: "More Partners" },
];

const outletTypes = [
  { label: "F&B", value: "F&B" },
  { label: "HotelStay", value: "HotelStay" },
  { label: "LaPerle", value: "LaPerle" },
];

const posTypes = [{ label: "Simphony", value: "Simphony" }];
const sortOrder = [{ value: "1", label: "1" }];
const nationalities = [
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Andorran",
  "Angolan",
  "Antiguans",
  "Argentinean",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Barbudans",
  "Batswana",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bhutanese",
  "Bolivian",
  "Bosnian",
  "Brazilian",
  "British",
  "Bruneian",
  "Bulgarian",
  "Burkinabe",
  "Burmese",
  "Burundian",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Cape Verdean",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Comoran",
  "Congolese",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Cypriot",
  "Czech",
  "Danish",
  "Djibouti",
  "Dominican",
  "Dutch",
  "East Timorese",
  "Ecuadorean",
  "Egyptian",
  "Emirian",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Ethiopian",
  "Fijian",
  "Filipino",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Greek",
  "Grenadian",
  "Guatemalan",
  "Guinea-Bissauan",
  "Guinean",
  "Guyanese",
  "Haitian",
  "Herzegovinian",
  "Honduran",
  "Hungarian",
  "I-Kiribati",
  "Icelander",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Ivorian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakhstani",
  "Kenyan",
  "Kittian and Nevisian",
  "Kuwaiti",
  "Kyrgyz",
  "Laotian",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Liechtensteiner",
  "Lithuanian",
  "Luxembourger",
  "Macedonian",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivan",
  "Malian",
  "Maltese",
  "Marshallese",
  "Mauritanian",
  "Mauritian",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Monacan",
  "Mongolian",
  "Moroccan",
  "Mosotho",
  "Motswana",
  "Mozambican",
  "Namibian",
  "Nauruan",
  "Nepalese",
  "New Zealander",
  "Nicaraguan",
  "Nigerian",
  "Nigerien",
  "North Korean",
  "Northern Irish",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Panamanian",
  "Papua New Guinean",
  "Paraguayan",
  "Peruvian",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Saint Lucian",
  "Salvadoran",
  "Samoan",
  "San Marinese",
  "Sao Tomean",
  "Saudi",
  "Scottish",
  "Senegalese",
  "Serbian",
  "Seychellois",
  "Sierra Leonean",
  "Singaporean",
  "Slovakian",
  "Slovenian",
  "Solomon Islander",
  "Somali",
  "South African",
  "South Korean",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Surinamer",
  "Swazi",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanese",
  "Tajik",
  "Tanzanian",
  "Thai",
  "Togolese",
  "Tongan",
  "Trinidadian or Tobagonian",
  "Tunisian",
  "Turkish",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbekistani",
  "Venezuelan",
  "Vietnamese",
  "Welsh",
  "Yemenite",
  "Zambian",
  "Zimbabwean",
];
const screens = [
  { value: "opening", label: "Opening" },
  { value: "home", label: "Home" },
  { value: "news", label: "News" },
  { value: "offers", label: "Offers" },
  // { value: "sports_and_events", label: "Sports And Events" },
  // { value: "benefits", label: "Benefits" },
];

const callToActions = [
  { value: "no_cta", label: "Nowhere" },
  { value: "news", label: "News" },
  { value: "offers", label: "Offers" },
  // { value: "events", label: "events" },
  { value: "partners", label: "Partners" },
];

const TRANSACTION_TYPES = ["All", "Earn", "Redeem"];

const TRANSACTION_MODES = ["All", "Earn", "Redeem"];
const TRANSACTION_SOURCE = ["All", "POS", "CMS", "AdminApp"];

const discountTypes = [
  {
    value: "ItemizerDiscount",
    label: "ItemizerDiscount",
  },

  {
    value: "OpenDiscount",
    label: "OpenDiscount",
  },

  {
    value: "SubTotalDiscount",
    label: "SubTotalDiscount",
  },
];

const discountValueTypes = [
  {
    value: "Percentage",
    label: "Percentage",
  },

  {
    value: "Amount",
    label: "Amount",
  },
];
const userImage =
  "https://i0.wp.com/www.miwatj.com.au/wp-content/uploads/placeholder-person.png?w=1024&ssl=1";
export {
  userImage,
  discountValueTypes,
  discountTypes,
  TRANSACTION_TYPES,
  TRANSACTION_MODES,
  TRANSACTION_SOURCE,
  callToActions,
  screens,
  nationalities,
  sortOrder,
  dummyValue,
  transactionData,
  salesData,
  users,
  transactions,
  profileData,
  countryCodes,
  guestNames,
  guestTransactionDetails,
  offers,
  news,
  templates,
  propertyTypes,
  privacyPolicyData,
  termsAndConditionsData,
  isTesting,
  permissionBased,
  outletTypes,
  posTypes,
  devMode,
  globalDateInputFormat,
  globalDateDisplayFormat,
};
