export default {
  create: "create",
  bulkUpload: "bulkUpload",
  edit: "edit",
  allowListingWithoutSearch: "allowListingWithoutSearch",
  delete: "delete",
  deactivate: "deactivate",
  sendNotification: "sendNotification",
  addLaperleTickets: "addLaperleTickets",
  addGuestPoints: "addGuestPoints",
  burnGuestPoints: "burnGuestPoints",
  reply: "reply",
  upgrade: "upgrade",
  downgrade: "downgrade",
  deleteOffer: "offer/delete",
  homeScreenVisibilityCreateOffer: "offer/create/homeScreenVisibility",
  homeScreenVisibilityEditOffer: "offer/edit/homeScreenVisibility",
};
