// Mock data
export const MOCK_USERS = [
  {
    id: "user-1",
    name: "John Smith",
    email: "john.smith@email.com",
    party_size: 2,
    reservation_time: "7:30 PM",
    status: "waiting",
    phone: "+1-555-0123",
    avatar: null,
  },
  {
    id: "user-2",
    name: "Sarah Johnson",
    email: "sarah.j@email.com",
    party_size: 4,
    reservation_time: "8:00 PM",
    status: "confirmed",
    phone: "+1-555-0456",
    avatar: null,
  },
  {
    id: "user-3",
    name: "Mike Wilson",
    email: "mike.w@email.com",
    party_size: 6,
    reservation_time: "8:30 PM",
    status: "waiting",
    phone: "+1-555-0789",
    avatar: null,
  },
  {
    id: "user-4",
    name: "Emily Davis",
    email: "emily.d@email.com",
    party_size: 3,
    reservation_time: "9:00 PM",
    status: "confirmed",
    phone: "+1-555-0321",
    avatar: null,
  },
];

export const MOCK_TABLES = [
  {
    id: "table-1",
    tableNumber: 1,
    tableType: "square-4",
    tableStatus: "available",
    position: { x: 150, y: 80 },
    width: 80,
    height: 60,
    capacity: 4,
  },
  {
    id: "table-2",
    tableNumber: 2,
    tableType: "round-6",
    tableStatus: "available",
    position: { x: 300, y: 80 },
    width: 80,
    height: 80,
    capacity: 6,
  },
  {
    id: "table-3",
    tableNumber: 3,
    tableType: "rectangle-6",
    tableStatus: "available",
    position: { x: 480, y: 80 },
    width: 60,
    height: 60,
    capacity: 6,
  },
  {
    id: "table-4",
    tableNumber: 4,
    tableType: "square-4",
    tableStatus: "available",
    position: { x: 150, y: 200 },
    width: 80,
    height: 60,
    capacity: 4,
  },
  {
    id: "table-5",
    tableNumber: 5,
    tableType: "round-6",
    tableStatus: "available",
    position: { x: 300, y: 200 },
    width: 70,
    height: 70,
    capacity: 4,
  },
  {
    id: "table-6",
    tableNumber: 6,
    tableType: "square-4",
    tableStatus: "available",
    position: { x: 480, y: 200 },
    width: 60,
    height: 50,
    capacity: 2,
  },
  {
    id: "table-8",
    tableType: "round-6",
    tableNumber: 8,
    tableStatus: "available",
    position: { x: 450, y: 320 },
    width: 80,
    height: 80,
    capacity: 6,
  },
];

// Table status configurations
export const TABLE_STATUSES = {
  available: {
    color: "bg-green-600",
    textColor: "text-green-600",
    label: "Available",
    badgeTextColor: "text-white",
  },
  seated: {
    color: "bg-blue-600",
    textColor: "text-blue-600",
    label: "Seated",
    badgeTextColor: "text-white",
  },
  cleaning: {
    color: "bg-yellow-600",
    textColor: "text-yellow-600",
    label: "Cleaning",
    badgeTextColor: "text-white",
  },
  maintenance: {
    color: "bg-gray-600",
    textColor: "text-gray-600",
    label: "Maintenance",
    badgeTextColor: "text-white",
  },
};
